name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gerar Snake (Dark + Light)
        uses: Platane/snk@v3
        with:
          github_user_name: GustavoMimoso
          outputs: |
            dist/snake.svg?palette=github-light
            dist/snake-dark.svg?palette=github-dark

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
          commit_message: "chore: update snake (dark + light)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
